# Generated by Django 5.1.3 on 2024-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_project_progress_projectmember_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('can_wait', 'Can Wait')], default='can_wait', max_length=20),
        ),
    ]
